Locale = {
	'Open': 'Megnyit',
	'Recent...': 'Mostanában...',
	'Save As...': 'Mentés mint...',
	'Undo': 'Vissza',
	'Redo': 'Előre',
	'Exit': 'Kilépés',
	'New': 'Új',
	'Do you want to exit?': 'Biztos ki akarsz lépni a programból?',
	'Yes': 'Igen',
	'Cancel': 'Mégse',
	'There are unsaved changes! Are you sure?': 'Vannak nem elmentett változtatások! Biztos folytatod?',
	'Database error:': 'Adatbázis hiba:',
	'Error fetching file: ': 'Fájl betöltése sikertelen: ',
	'Failed to load ': 'Nem sikerült betölteni ',
	'Error during file open process:': 'Hiba a fájl megnyitása közben: ',
	'Error saving:': 'Hiba mentés közben: ',
	'Exception:': 'Kivétel:',
	'No file chosen': 'Nincs fájl kiválasztva',
	'Invalid or expired credentials': 'Érvénytelen vagy lejárt hitelesítő adatok',  // TODO non-existent string
	'No matching mChunk found for chunk with id: ': 'Nincs egyező mChunk azonosító: ',
	'Document Loaded': 'Dokumentum betöltve',
	'Document Saved': 'Dokumentum mentve',
	'Document changed outside, history action is disabled': 'A dokumentum megváltozott, az előre/hátra lépés le lett tiltva',
	'Show +1 sentence': '+1 mondat mutatása',
	'Table View': 'Táblázatos nézet',
	'Normal View': 'Normál nézet',
	'': ''
}
