Locale = {
	'Open': 'Megnyit',
	'Recent...': 'Mostanában...',
	'Save As...': 'Mentés mint...',
	'Undo': 'Vissza',
	'Redo': 'Előre',
	'Exit': 'Kilépés',
	'New': 'Új',
	'New Text for Metaphor Detection': 'Új szöveg metafora detektáláshoz',
	'File Name': 'Fájlnév',
	'Content': 'Tartalom',
	'Submit': 'Beküldés',
	'Please fill in all fields': 'Kérjük, töltse ki az összes mezőt',
	'Network error': 'Hálózati hiba',
	'Do you want to exit?': 'Biztos ki akarsz lépni a programból?',
	'Yes': 'Igen',
	'Cancel': 'Mégse',
	'There are unsaved changes! Are you sure?': 'Vannak nem elmentett változtatások! Biztos folytatod?',
	'Unknown Error': 'Ismeretlen hiba',
	'Document Loaded': 'Dokumentum betöltve',
	'Document Saved': 'Dokumentum mentve',
	'Document changed outside, history action is disabled': 'A dokumentum megváltozott, az előre/hátra lépés le lett tiltva',
	'Show +1 sentence': '+1 mondat mutatása',
	'Table View': 'Táblázatos nézet',
	'Normal View': 'Normál nézet',
	'': ''
}
